dvsa/cvs-svc-technical-records

README.md, package-lock.json, package.json, serverless.yml, src/models/TechRecordsDAO.js
Merging to a single branch for testing
=> CVSB-4791 - Add XRay tracing. All tests pass.

src/services/TechRecordsService.ts, tests/resources/technical-records.json, tests/unit/TechRecordsService.unitTest.ts
Branch will be merged and tested in 4924
=> CVSB-9346 Bugfix return euroStandard as a string

serverless.yml, src/assets/Enums.ts, src/config/config.yml, src/functions/updateTechRecordStatus.ts, src/services/TechRecordsService.ts, tests/integration/updateTechRecordStatus.intTest.ts, tests/unit/configuration.unitTest.ts, tests/unit/handler.unitTest.ts
This PR contains the logic to update tech-records in dynamoDB
=> CVSB-4867 & CVSB-7049

src/utils/AdrValidation.ts, src/utils/PayloadValidation.ts, tests/resources/technical-records.json, tests/unit/TechRecordsService.unitTest.ts, tests/unit/insertTechRecordsList.unitTest.ts
https://jira.dvsacloud.uk/browse/CVSB-11487
=> Feature/cvsb 11487 Handling of null values within migrated anonymised data

serverless.yml, src/assets/Enums.ts, src/config/config.yml, src/functions/updateEuVehicleCategory.ts, src/services/TechRecordsService.ts, tests/features/step_definitions/10209.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10210.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10211.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10213.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10214.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10752.ACs.feature.steps.intTest.ts, tests/features/step_definitions/12013.ACs.feature.steps.intTest.ts, tests/features/step_definitions/4924.ACs.feature.steps.intTest.ts, tests/features/step_definitions/7051.ACs.feature.steps.intTest.ts, tests/features/step_definitions/7743.ACs.feature.steps.intTest.ts, tests/features/step_definitions/7885.ACs.feature.steps.intTest.ts, tests/features/step_definitions/8677.ACs.feature.steps.intTest.ts, tests/integration/TechRecordsFunction.intTest.ts, tests/integration/checkExistsFunctionPaths.intTest.ts, tests/integration/techRecords.intTest.ts, tests/integration/techRecordsDao.intTest.ts, tests/integration/updateEuVehicleCategroy.intTest.ts, tests/integration/updateTechRecordStatus.intTest.ts, tests/resources/technical-records.json, tests/unit/TechRecordsService.unitTest.ts, tests/unit/configuration.unitTest.ts, tests/unit/handler.unitTest.ts
https://jira.dvsacloud.uk/browse/CVSB-11333
=> CVSB-11333 new function added for updating EuVehicleCategory with code coverage

tests/resources/technical-records.json
Updated tech records to work with the FE regression tests.
=> [CVSB-14536] Fixes for Mobile App regression failures (2020-04-23)

src/functions/updateTechRecords.ts, src/services/TechRecordsService.ts, src/utils/PayloadValidation.ts, src/utils/formatErrorMessage.ts, tests/features/step_definitions/10210.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10211.ACs.feature.steps.intTest.ts, tests/integration/TechRecordsFunction.intTest.ts, tests/integration/techRecords.intTest.ts, tests/unit/TechRecordsService.unitTest.ts
https://jira.dvsacloud.uk/browse/CVSB-14486
Changed the structure of the error object returned when validation fails, in order to return all error messages from Joi
=> Feature/cvsb 14486 - changed validation error object response

serverless.yml, src/assets/Enums.ts, src/config/config.yml, src/functions/postTechRecords.ts, src/functions/updateTechRecords.ts, src/models/TechRecordsDAO.ts, src/services/TechRecordsService.ts, src/utils/PayloadValidation.ts, tests/features/step_definitions/10209.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10211.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10214.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10813.ACs.feature.steps.intTest.ts, tests/features/step_definitions/7885.ACs.feature.steps.intTest.ts, tests/features/step_definitions/8677.ACs.feature.steps.intTest.ts, tests/integration/TechRecordsFunction.intTest.ts, tests/integration/checkExistsFunctionPaths.intTest.ts, tests/integration/techRecords.intTest.ts, tests/resources/technical-records.json, tests/unit/TechRecordsDao.unitTest.ts, tests/unit/TechRecordsService.unitTest.ts
https://jira.dvsacloud.uk/browse/CVSB-10478
=> Feature/cvsb 10478 - update attributes outside techRecords array

@Types/ITechRecord.d.ts, src/utils/AdrValidation.ts
https://jira.dvsacloud.uk/browse/CVSB-10155
=> CVSB- 10155 added adrCertificateNotes and tankTypeAppNo optional

src/assets/Enums.ts, src/services/TechRecordsService.ts, src/utils/CarValidations.ts, src/utils/CommonSchema.ts, src/utils/LgvValidations.ts, src/utils/MotorcycleValidations.ts, src/utils/PayloadValidation.ts, src/utils/PsvValidations.ts, src/utils/ValidationUtils.ts, tests/resources/technical-records.json, tests/unit/TechRecordsService.unitTest.ts, tests/unit/payloadValidation.unitTest.ts
Create/Update and error handling for all three new vehicle types: car, lgv and motorcycle.
https://jira.dvsacloud.uk/browse/CVSB-11814
https://jira.dvsacloud.uk/browse/CVSB-10328
=> Feature/cvsb 11814 - Create/Update LGV/CAR/MOTORCYCLE

README.md, src/services/TechRecordsService.ts
enable feature flag build for ADR on PUT requests
=> fix(feat-14145): fix feature flag

package.json
remove postinstall hook to accomodate CI/CD
=> Fix install

tests/resources/technical-records.json
https://jira.dvsacloud.uk/browse/CVSB-17424
Added entries in seed file needed for automated tests
=> CVSBB-9644 - added entries in seed file

.gitignore, .npmrc, .nsprc, package-lock.json, package.json
fix dependencies and update audit script
=> feat(feature/CVSB-17585) fix high vulnverability

src/assets/Enums.ts, src/functions/updateEuVehicleCategory.ts, src/services/TechRecordsService.ts, tests/integration/updateEuVehicleCategroy.intTest.ts, tests/unit/TechRecordsService.unitTest.ts
Ticket to make sure tech records are being updated accurately, in regards to EU vehicle category.
https://jira.dvsacloud.uk/browse/CVSB-17402
=> CVSB-17402 - set audit details for EU vehicle category update

tests/resources/technical-records.json
Added the correct values in the vehicle subclass for some tech records
https://jira.dvsacloud.uk/browse/CVSB-18277
=> CVSB-18277 - correct vehicle subclass

README.md
fix: add nvm instructions and set installation automatically on postinstall
fix(install): remove postinstall hook
=> fix(install): add dynamodb missing pkg and nodejs metadata

package-lock.json, package.json
One line description
[link to ticket number]()
=> fix(cvsb-19600): fix high audit vulns

package.json, src/domain/Processors/TrailerProcessor.ts, src/domain/Processors/VehicleProcessor.ts, src/handlers/TechRecordsListHandler.ts, src/models/TechRecordsDAO.ts, tests/unit/TechRecordsService.unitTest.ts, tests/unit/domain/addProvisional.unitTest.ts, tests/unit/domain/updateVehicle.unitTest.ts
Adding pagination to getBySearchTerm method
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-19059)
=> chore(cvsb-19059): adding pagination to getbysearchterm method

tests/resources/technical-records.json
Add in 3 synthetic data records
Create 3 synthetic data pieces for the tech records
[link to ticket number](https://jira.dvsacloud.uk/browse/CB2-3452)
=> feat(cb2-2890): Add in 3 synthetic data records

package-lock.json, package.json
[VTA-505](https://jira.dvsacloud.uk/browse/VTA-505)
=> feat(vta-568): resolve high vulns as per npm audit

src/assets/Enums.ts, src/functions/getTechRecords.ts, src/handler.ts, src/models/HTTPError.ts, src/models/HTTPResponse.ts, src/models/ILogMessage.ts, src/utils/Validator.ts, tests/integration/TechRecordsFunction.intTest.ts, tests/unit/getTechRecordsFunction.unitTest.ts
Add validation for parameters and additional request/response logging to Tech Record Service.
[link to ticket number](https://dvsa.atlassian.net/browse/VTA-694)
=> feat(VTA-695): added parameter validation and additional logging

tests/resources/technical-records.json
[CB2-4887](https://dvsa.atlassian.net/browse/CB2-4887)
=> data(cb2-4887): adds vtm test data for psv validation groups

src/handlers/TechRecordStatusHandler.ts
Notifiable alteration check - Test Type: 38: added to notifiableAlterationIds 
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-3798)
[Regression Tests](https://jenkins.cvs.dvsacloud.uk/job/UPDATE__BRANCH/job/job_feature_test_backend/2407/DVSA_20CVS_20Backend_20Automation/)
=> feature(cb2-3798): added testypeid 38 to notifiableAlterationIds 

src/assets/Enums.ts, src/functions/getTechRecords.ts, src/handler.ts, src/models/HTTPError.ts, src/models/HTTPResponse.ts, src/models/ILogMessage.ts, src/utils/Validator.ts, tests/integration/TechRecordsFunction.intTest.ts, tests/unit/getTechRecordsFunction.unitTest.ts
Merge from holding branch VTADEV-31 into develop
[VTA-695](https://dvsa.atlassian.net/browse/VTA-695)
=> VTA-695: Add validation for parameters and additional request/response logging

tests/resources/technical-records.json
Add new mocks with amended vins for future work
[https://dvsa.atlassian.net/browse/CB2-6898](6898)
=> feat(cb2-6898): update tech records for new records with new vins

src/domain/Processors/TrailerProcessor.ts, src/domain/Processors/VehicleProcessor.ts, src/utils/record-completeness/ComputeRecordCompleteness.ts, src/utils/record-completeness/NonCoreMandatoryValidations.ts, tests/unit/ComputeRecordCompleteness.unitTest.ts
- Rewrite the record completeness workflow focusing on simplicity and readability.
[CB2-6869](https://dvsa.atlassian.net/browse/CB2-6869)
=> feature(cb2-6869): rewrite the calculation workflow for record completeness

package-lock.json, package.json, tests/resources/technical-records.json
Add motorcycle seed data. Also include a package bump.
[CB2-7009](https://dvsa.atlassian.net/browse/CB2-7009)
Unit, Integration, and Regression tests have all been ran and their results are as expected.
=> CB2-7009 Add supporting seed data

tests/resources/stitchedUpTechRecords.json
There is a failing integration test because some dates were changed
=> fix(*): fix failing integration test

tests/resources/technical-records.json
Vins should be on vehicle records and not on tech records
=> fix(cb2-6898): remove vins on tech records

@Types/TechRecords.d.ts, src/utils/record-completeness/ComputeRecordCompleteness.ts, src/utils/validations/CommonSchema.ts, tests/unit/ComputeRecordCompleteness.unitTest.ts, tests/unit/domain/addProvisional.unitTest.ts
- Add a new flag to track record visibility on VTA
[CB2-6869](https://dvsa.atlassian.net/browse/CB2-6869)
=> feat(cb2-6869): add a flag to track record visibility in vta

jest.config.js, package.json, src/domain/Processors/VehicleProcessor.ts, tests/integration/updateEuVehicleCategroy.intTest.ts, tests/resources/stitchedUpTechRecords.json, tests/resources/technical-records.json, tests/unit/TechRecordsService.unitTest.ts
Enable updateEuVehicleCategory to handle vehicles with vin changes
[CB2-6921](https://dvsa.atlassian.net/browse/CB2-6921)
=> CB2-6921: enable updateEuVehicleCategory to handle vehicles with vin changes

src/assets/Enums.ts, src/utils/validations/ValidationUtils.ts, tests/unit/payloadValidation.unitTest.ts
[CB2-397](https://dvsa.atlassian.net/browse/CB2-397)
=> feat(cb2-397): add new vehicle body types

src/utils/record-completeness/NonCoreMandatoryValidations.ts, src/utils/validations/AdrValidation.ts, src/utils/validations/CarValidations.ts, src/utils/validations/CommonSchema.ts, src/utils/validations/HgvValidations.ts, src/utils/validations/LgvValidations.ts, src/utils/validations/MotorcycleValidations.ts, src/utils/validations/PsvValidations.ts, src/utils/validations/TrlValidations.ts, tests/features/10210.ACs.feature, tests/features/10211.ACs.feature, tests/features/step_definitions/10210.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10211.ACs.feature.steps.intTest.ts
=> feat(cb2-7248): remove mandatory validation

src/utils/record-completeness/CoreMandatoryValidations.ts
[CB2-7047](https://dvsa.atlassian.net/browse/CB2-7047)
=> fix(cb2-7047): noWheelsDriven allow null

src/domain/Processors/VehicleProcessor.ts, tests/unit/domain/updateVehicle.unitTest.ts
PR to adjust backend validation to ignore archived technical records when looking at VRM history
[CB2-5698](https://dvsa.atlassian.net/browse/CB2-5698)
=> feature(cb2-5698): amend vrm

src/domain/VehicleFactory.ts, src/utils/validations/SmallTrailerValidation.ts
- Allow notes for small trailers.
[CB2-7027](https://dvsa.atlassian.net/browse/CB2-7027)
=> fix(cb2-7397): allow notes for small trailers

src/assets/Enums.ts, src/domain/Processors/HgvProcessor.ts, src/domain/Processors/PsvProcessor.ts, src/domain/Processors/TrailerProcessor.ts, src/domain/Processors/VehicleProcessor.ts, src/functions/postTechRecords.ts, src/handlers/NumberGenerator.ts, src/models/TechRecordsDAO.ts, tests/features/step_definitions/10209.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10214.ACs.feature.steps.intTest.ts, tests/features/step_definitions/10813.ACs.feature.steps.intTest.ts, tests/features/step_definitions/7885.ACs.feature.steps.intTest.ts, tests/features/step_definitions/8677.ACs.feature.steps.intTest.ts, tests/integration/checkExistsFunctionPaths.intTest.ts, tests/integration/techRecords.intTest.ts, tests/unit/TechRecordsService.unitTest.ts
[CB2-7058](https://dvsa.atlassian.net/browse/CB2-7058)
[CB2-7059](https://dvsa.atlassian.net/browse/CB2-7059)
=> feat(cb2-7058)/feat(cb2-7059): Generate C and Z numbers

src/functions/postTechRecords.ts
[CB2-7059](https://dvsa.atlassian.net/browse/CB2-7059)
=> fix(cb2-7059): creating psvs and hgvs breaks because of trailerId

tests/resources/technical-records.json
[VTA-1131](https://dvsa.atlassian.net/browse/VTA-1131)
=> VTA-1131: New seed data for VTA QA

src/domain/Processors/VehicleProcessor.ts
[CB2-7527](https://dvsa.atlassian.net/browse/CB2-7527)
=> fix(cb2-7527): fix logic deciding to validate primaryVrm

tests/resources/technical-records.json
=> feat(cb2-7355): fixes tyreSize seed data

src/utils/validations/CommonSchema.ts, tests/resources/technical-records.json
=> feat(cb2-7355): doc gen - update date schema for plates

tests/resources/technical-records.json
This adds the 3 example tech records required for LGV testing
[VTA-1288](https://dvsa.atlassian.net/browse/VTA-1288)
=> VTA-1288: Add 3 Tech Records to Seed Data for LGV Functionality

docs/tech-records-api.yml
_Add new endpoint definition for amend VIN to swagger docs_
[CB2-7602](https://dvsa.atlassian.net/browse/CB2-7602)
=> docs(cb2-7602): amend vin swagger

tests/resources/technical-records.json
Correct the data, Kirsty QA to confirm now
[VTA-1307](https://dvsa.atlassian.net/browse/VTA-1307)
=> VTA-1307: fix correct subclass formatting in seed data

@Types/TechRecords.d.ts, docs/tech-records-api.yml, src/assets/Enums.ts, src/utils/validations/CommonSchema.ts, src/utils/validations/TrlValidations.ts, tests/resources/technical-records.json
New validation for letters of authorisation and also adds a new trailer of id C111222 to the seed data
[CB2-7471](https://dvsa.atlassian.net/browse/CB2-7471)
=> feat(cb2-7471): trailer into service letter validation and extra seed data

src/functions/updateVin.ts, src/services/TechRecordsService.ts, tests/unit/TechRecordsService.unitTest.ts
[CB2-5697](https://dvsa.atlassian.net/browse/CB2-5697)
=> fix(cb2-5697): historic VRMs

src/services/TechRecordsService.ts
[CB2-5697](https://dvsa.atlassian.net/browse/CB2-5697)
=> fix(cb2-5697): stagger created at dates

src/services/TechRecordsService.ts
=> fix(cb2-5697): createdAt fix

src/assets/Enums.ts, src/domain/Processors/CarProcessor.ts, src/domain/Processors/LgvProcessor.ts, src/domain/Processors/MotorcycleProcessor.ts, src/utils/validations/CarValidations.ts, src/utils/validations/LgvValidations.ts, src/utils/validations/MotorcycleValidations.ts, src/utils/validations/SmallTrailerValidation.ts, tests/unit/domain/processors/CarProcessor.unitTest.ts, tests/unit/domain/processors/LgvProcessor.unitTest.ts, tests/unit/domain/processors/MotorcycleProcessor.unitTest.ts
[CB2-6641](https://dvsa.atlassian.net/browse/CB2-6641)
[CB2-7044](https://dvsa.atlassian.net/browse/CB2-7044)
=> Feat(cb2-6641): correct the validation for light vehicles

src/domain/Processors/VehicleProcessor.ts
The api now won't error if you give it something it doesn't want, it just strips it from the payload.
[https://dvsa.atlassian.net/browse/CB2-6394](cb2-6394)
=> fix(cb2-6394): allow it to strip unknown values but allow them through

src/utils/validations/CarValidations.ts, src/utils/validations/LgvValidations.ts, src/utils/validations/MotorcycleValidations.ts
[CB2-7044](https://dvsa.atlassian.net/browse/CB2-7044)
=> feat(cb2-7044): fix validation

src/assets/Enums.ts, src/domain/VehicleFactory.ts, src/utils/validations/SmallTrailerValidation.ts, tests/unit/domain/processors/SmallTraillerProcessor.unitTest.ts
[CB2-7727](https://dvsa.atlassian.net/browse/CB2-7727)
=> fix(cb2-7727): remove the small trailer type

src/assets/Enums.ts, src/domain/Processors/CarProcessor.ts, src/domain/Processors/LgvProcessor.ts, src/domain/Processors/MotorcycleProcessor.ts, src/domain/Processors/VehicleProcessor.ts, src/domain/VehicleFactory.ts, src/utils/validations/CarValidations.ts, src/utils/validations/LgvValidations.ts, src/utils/validations/MotorcycleValidations.ts, src/utils/validations/SmallTrailerValidation.ts, tests/unit/domain/processors/CarProcessor.unitTest.ts, tests/unit/domain/processors/LgvProcessor.unitTest.ts, tests/unit/domain/processors/MotorcycleProcessor.unitTest.ts, tests/unit/domain/processors/SmallTraillerProcessor.unitTest.ts
[CB2-7727](https://dvsa.atlassian.net/browse/CB2-7727)
[CB2-6394](https://dvsa.atlassian.net/browse/CB2-6394)
[CB2-7044](https://dvsa.atlassian.net/browse/CB2-7044)
[CB2-7727](https://dvsa.atlassian.net/browse/CB2-7727)
=> feat(cb2-7727, cb2-6394, cb2-7044): light vehicles validation

src/handlers/TechRecordStatusHandler.ts
Adds the test codes to the list of tests that call update tech record status 
[CB2-7881](https://dvsa.atlassian.net/browse/CB2-7881)
=> feat(cb2-7881): adds the test codes to the list of tests that call update tech record status

tests/resources/technical-records.json
Addition of new seed data to be used by the UI automation pack.
[link to ticket number](https://dvsa.atlassian.net/browse/VTA-1452)
=> feat(vta-1452): new seed data for qa

src/handlers/TechRecordStatusHandler.ts
Coif test 142, 143 should promote provisional to current
[CB2-8424](https://dvsa.atlassian.net/browse/CB2-8424)
=> feat(cb2-8424): allow coif test to promote tech record

src/handlers/TechRecordStatusHandler.ts
add coif restest to coif tests
[CB2-8671](https://dvsa.atlassian.net/browse/CB2-8671)
=> feat(cb2-8671): add coif restests to coif tests

.github/workflows/pr-checks.yml, patches/dynamodb-localhost+0.0.9.patch
Fixes integration tests. DynamoDB local had an update which increased validation around aws keys. quick fix to be able to deploy services.
[link to ticket number]()
=> fix(cb2-000): fix integration tests

src/domain/Processors/VehicleProcessor.ts, src/functions/addProvisionalTechRecord.ts, src/functions/postTechRecords.ts, src/functions/updateTechRecords.ts, src/handlers/AuditDetailsHandler.ts, tests/integration/techRecords.intTest.ts, tests/integration/updateEuVehicleCategory.intTest.ts, tests/resources/technical-records.json, tests/unit/TechRecordsService.unitTest.ts
Improves validation on create technical record
Also ensures createdAt dates are unique when updating a technical record's eu vehicle category.
[CB2-8637](https://dvsa.atlassian.net/browse/CB2-8637)
=> fix(cb2-8637): improve validation on create technical record

src/functions/updateTechRecordStatus.ts, src/handlers/TechRecordStatusHandler.ts, tests/integration/updateTechRecordStatus.intTest.ts, tests/unit/handler.unitTest.ts
Worth saying there is a lot of linting changes here
[https://dvsa.atlassian.net/browse/CB2-8661](8661)
=> feat(cb2-8661): remove validation as moved to earlier step

.github/workflows/pr-checks.yml, package-lock.json, package.json
Added Sonar dev dependency
Added Scanner job
[CB2-10087](https://dvsa.atlassian.net/browse/CB2-10087)
=> feat(cb2-10067): added scanner job

manifest.json, tests/resources/technical-records.json
Fix to the technical record which is causing an error to be continuously thrown in the logs.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-12224)
=> CB2-12224: Data Fix
