dvsa/cvs-svc-technical-records

- @Types/ITechRecord.d.ts
- src/assets/Enums.ts
- src/services/TechRecordsService.ts
- tests/features/4924.ACs.feature
- tests/features/step_definitions/4924.ACs.feature.steps.intTest.ts
- tests/resources/technical-records.json
- tests/unit/TechRecordsService.unitTest.ts
- tests/unit/insertTechRecordsList.unitTest.ts
- tests/util/dbOperations.ts
I branched this change from CVSB-7885 to retrieve the jest-cucumber setup.
Redundant integration tests were copied as per guidelines.
> CVSB-4924 Updated API specs to cover ADR details

- @Types/IUserDetails.ts
- serverless.yml
- src/assets/Enums.ts
- src/config/config.yml
- src/functions/addProvisionalTechRecord.ts
- src/functions/archiveTechRecordStatus.ts
- src/functions/updateTechRecords.ts
- src/services/TechRecordsService.ts
- src/utils/CommonSchema.ts
- tests/integration/archiveTechRecordStatus.intTest.ts
- tests/integration/techRecords.intTest.ts
- tests/unit/TechRecordsService.unitTest.ts
- tests/unit/configuration.unitTest.ts
- tests/unit/handler.unitTest.ts
Backend service update to archive a tech-record, to add a new provisional tech-record and to manually change the statusCode on a tech-record
Link to the closed PR (for history): https://github.com/dvsa/cvs-svc-technical-records/pull/121
> Feature/cvsb 10195 - archive, add provisional record and statusCode change

- serverless.yml
- src/functions/updateTechRecordStatus.ts
- src/services/TechRecordsService.ts
- tests/integration/updateTechRecordStatus.intTest.ts
- tests/unit/TechRecordsService.unitTest.ts
technical records' status to be updated from provisional to current if a vehicle passes via 'PASS' or 'PRS' for a first test/ notifiable alteration test carried out via the app or VTM (as part of a contingency process).
https://jira.dvsacloud.uk/browse/CVSB-10316
> feature/CVSB-10316 - update statusCode after firstTest/notifiable alt

- src/assets/Enums.ts
- tests/resources/technical-records.json
https://jira.dvsacloud.uk/browse/CVSB-15612
Backend service update needed to change the values in the vehicleSubclass enum to lower case to match the ones in the test-type taxonomy.
> CVSB-15612 - vehicleSubclass enum to lower case

- src/models/TechRecordsDAO.ts
- src/utils/validations/AdrValidation.ts
- tests/unit/TechRecordsDao.unitTest.ts
Update the GET request, on the vehicles (tech records) backend service, to ensure that the search criteria is capitalised before it hits the DynamoDB
POST/PUT -> vin, partialVin, primaryVrm, trailerId, secondaryVrm to upper case
https://jira.dvsacloud.uk/browse/CVSB-10185
> feature/CVSB-10185 - GET/POST/PUT upper case conversion

- package-lock.json
- tests/resources/technical-records.json
This code change adds additional tech-records to the .json seed file to allow QA to properly test the change.
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-15130)
> chore(cvsb-15130): added additional tech-records for qa automated tests

- tests/resources/technical-records.json
Adds technical record data for development, testing and sign-off for PSV validation groups 1, 2, and 15
[CB2-4887](https://dvsa.atlassian.net/browse/CB2-4887)
> data(cb2-4887): adds vtm test data for psv validation groups

- tests/resources/technical-records.json
Adds HGV and TRL annual test seed data
[cb2-5414](https://dvsa.atlassian.net/browse/CB2-5414)
> feat(cb2-5414): adds hgv and trl annual test seed data

- api/swagger/swagger.yaml
- docs/tech-records-api.yml
- package-lock.json
- src/assets/Enums.ts
- tests/resources/technical-records.json
This PR includes the changes required to allow a vehicle configuration of 'long semi-trailer', as per option 1 on Jira ticket.
[VTA-761](https://dvsa.atlassian.net/browse/VTA-761)
> VTA-761: Update VTA BE APIs to cater for long semi-trailer vehicle configuration

- src/utils/validations/HgvValidations.ts
- src/utils/validations/TrlValidations.ts
- Make `width`, `length` and `frontAxleToRearAxle` fields optional.
[CB2-5702](https://dvsa.atlassian.net/browse/CB2-5702)
> feat(cb2-5702): fix the validation for hgv and trl dimension fields

- @Types/TechRecords.d.ts
- src/handlers/TechRecordsListHandler.ts
- src/models/TechRecordsDAO.ts
- tests/integration/techRecords.intTest.ts
- tests/resources/stitchedUpTechRecords.json
- tests/resources/technical-records.json
When a GET request is made to query the DynamoDB based on systemNumber, the API will now stitch together any DynamoDB records which have the same `systemNumber` but different `vin`. 
The stitching process involves pushing the objects from the `techRecord` array of the DynamoDB record with the **old** `vin` into the techRecord array of the DynamoDB record with the **newest** `vin`. 
The `vin` of a `techRecord` object at it's point in history is retained by adding a new `historicVin` attribute to each `techRecord` object.
The vehicle identifier attributes at the base of the returned record are the vehicle's **_current_** identifiers.
Other changes:
- Refactoring of the Dynamo query method
- Amending new seed data to be more realistic (have chronological `createdAt` dates)
- Fix bug where if …
> feat(cb2-6902): handle vehicle with changed vin in get request response

- .github/workflows/pr-checks.yml
- scripts/setup.ts
- scripts/teardown.ts
- tests/integration/TechRecordsFunction.intTest.ts
- failing integration tests don't return non-zero exit code
- adding a github action to run the prepush script on PRs
[CB2-6735](https://dvsa.atlassian.net/browse/CB2-6735)
> fix(cb2-6735): failing integration tests don't return non-zero exit code

- src/domain/Processors/VehicleProcessor.ts
- tests/integration/updateTechRecordStatus.intTest.ts
Check and make sure that update endpoint still works with multiple vins. This repairs the code to allow it and adds tests.
[https://dvsa.atlassian.net/browse/CB2-6923](6923)
> feat(cb2-6923): repair and test update endpoint for multiple vins

- @Types/TechRecords.d.ts
- src/utils/validations/CarValidations.ts
- src/utils/validations/HgvValidations.ts
- src/utils/validations/LgvValidations.ts
- src/utils/validations/MotorcycleValidations.ts
- src/utils/validations/PsvValidations.ts
PR to add historic primary and secondary vrm fields to the joi schemas
[CB2-5698](https://dvsa.atlassian.net/browse/CB2-5698)
> feat(cb2-5698): added historic vrms to validation schemas

- src/utils/record-completeness/CoreMandatoryValidations.ts
- tests/unit/ComputeRecordCompleteness.unitTest.ts
Update the rec completeness calculation to not need wheels driven to be provided, except still on motorcycles.
[https://dvsa.atlassian.net/browse/CB2-7047](7047)
> Feat(cb2-7047): update compute record completeness with new wheels driven logic

- src/domain/Processors/VehicleProcessor.ts
[CB2-7504](https://dvsa.atlassian.net/browse/CB2-7504)
> fix(cb2-7504): fully update the new tech records instead of merging it with the old

- src/domain/Processors/VehicleProcessor.ts
- tests/integration/techRecords.intTest.ts
CB2-7330
CB2- 5698
Work to retain historical VRM's so they show as the primary and secondary vrms as they were at the time the record was archived.
> feat(cb2-7330): add historical vrms

- src/domain/Processors/VehicleProcessor.ts
- src/models/TechRecordsDAO.ts
- tests/integration/techRecords.intTest.ts
- tests/unit/domain/updateVehicle.unitTest.ts
Removes lines of code to add the old primary VRM to the secondary array, which is functionality we don't want when amending the VRM to correct an error - the payload for the new primary and secondary VRMs is provided by VTM
[CB2-6178](https://dvsa.atlassian.net/browse/CB2-6178)
[CB2-5698](https://dvsa.atlassian.net/browse/CB2-5698)
> feat(cb2-6178): remove push to secondary vrms

- src/domain/Processors/PsvProcessor.ts
CB2-7535:
techRecord.brakes.brakeCode can be sent undefined, this causes an error which doesn't get caught, I think this will allow PSV skeleton records to change VRM
> fix(cb2-7535): skeleton psv records can't change vrm

- src/assets/Enums.ts
- src/utils/validations/TrlValidations.ts
- tests/resources/technical-records.json
PR to add missing fields for letters of authorisation to the backend validation
[CB2-7471](https://dvsa.atlassian.net/browse/CB2-7471)
> feat(cb2-7471): letters validation

- tests/resources/technical-records.json
Added various specialist test records provided by QA to the seed data to allow them to add the relevant tests to the regression packs.
[VTA-1296](https://dvsa.atlassian.net/browse/VTA-1296)
> VTA-1296: Add Specialist Test Seed Data

- @Types/ITechRecord.d.ts
- src/domain/Processors/VehicleProcessor.ts
- tests/integration/archiveTechRecordStatus.intTest.ts
- tests/resources/technical-records.json
CB2-7330:
when archiving a tech record the vrm's are stored as historic VRM's on the record in the interest of displaying them as they were when the record was archived.
> feat(cb2-7330) Retain VRM's on archive

- src/functions/updateVin.ts
- src/models/TechRecordsDAO.ts
- src/services/TechRecordsService.ts
- tests/integration/TechRecordsFunction.intTest.ts
- tests/unit/TechRecordsService.unitTest.ts
- tests/unit/domain/updateVin.unitTest.ts
- Adds ability to update to previously used vin
- Fixes the issue where the partial vin was not being updated
- Fixed an issue where validation errors were not being properly sent over locally (postman) (and maybe in AWS?)
[CB2-7668](https://dvsa.atlassian.net/browse/CB2-7668)
> fix(cb2-7668): unable to update to previously used vin

- @Types/TechRecords.d.ts
- src/domain/Processors/SmallTrailerProcessor.ts
- src/utils/record-completeness/ComputeRecordCompleteness.ts
- tests/features/step_definitions/10213.ACs.feature.steps.intTest.ts
- tests/unit/ComputeRecordCompleteness.unitTest.ts
- Generate IDs for small trailers.
- Update the record completeness schema for small trailers' non-mandatory fields.
[CB2-7727](https://dvsa.atlassian.net/browse/CB2-7727)
> fix(cb2-7727): enable generating trailer ids for small trailers and update their completeness calcs

- src/assets/Enums.ts
- src/domain/Processors/VehicleProcessor.ts
- tests/unit/TechRecordsService.unitTest.ts
This is to resolve the following issues:
- Where an error is thrown when trying to update the eu vehicle category where there is more than one
- Allow the eu vehicle category to be updated for more than one technical record
- Change the reasonForCreation field to say: Update to EU Vehicle Category for all tech records
[VTA-468](https://dvsa.atlassian.net/browse/VTA-468)
[VTA-531](https://dvsa.atlassian.net/browse/VTA-531)
> feat(VTA-468): update rules for eu category

- @Types/ITechRecord.d.ts
- @Types/TechRecords.d.ts
- src/utils/validations/TrlValidations.ts
CB2-7021:
Added the batchId to the tech record as an optional input for trailers.
> feat(cb2-7021): batch trailer creation

- src/domain/Processors/SmallTrailerProcessor.ts
- src/domain/Processors/TrailerProcessor.ts
[CB2-7946](https://dvsa.atlassian.net/browse/CB2-7946)
> fix(cb2-7946): do not save trailer ids as primary vrms

- src/domain/Processors/VehicleProcessor.ts
remove primary vrms if not sent
[CB2-7946](https://dvsa.atlassian.net/browse/CB2-7946)
> fix(Cb2-7946): remove primary vrms from trailers

- src/domain/VehicleFactory.ts
O2 eu vehicle category identifies small trailers
[CB2-7951](https://dvsa.atlassian.net/browse/CB2-7951)
> feat(cb2-7951): o2 eu vehicle category for small trailers

- tests/resources/technical-records.json
QA has been requested by VTM to change the system numbers and advised to start each number with a 9 i.e. 90000001 to differentiate from VTM.
[link to ticket number](https://dvsa.atlassian.net/browse/VTA-1492)
> feat(VTA-1492): UI Auto Update Seed Data

- src/utils/validations/HgvValidations.ts
- src/utils/validations/PsvValidations.ts
- src/utils/validations/TrlValidations.ts
changed body make and chassis make max length to 50
Related issue: [CB2-8830](https://dvsa.atlassian.net/browse/CB2-8830)
> fix(cb2-8830):changed body make and chassis make max length to 50
